version: '3.8'
services:
  php-compose-environment:
    build:
      context: ./php
    container_name: php_api_container
    image: php:8.0-apache
    volumes:
      - my_php_data:/var/www/html/
    ports:
      - 8000:80
volumes:
  
